### ISSUE TITLE
Ensure vault target is correct for given template

### ISSUE THREAD

**Issue by 7hunderbird** [jhunt/safe#27]
From `codex`:

All templates that need to use `safe` should verify that the user is targeted to the Vault they want to use, before we go blindly generating credentials and stuffing them in the vault.

**Comment by jhunt** [comment]
This has nothing to do with safe itself.  Issues will need to be raised in the appropriate `starkandwayne/*-deployment` repos.

**Comment by 7hunderbird** [comment]
Of the 7 deployments we're creating and managing at this time it appears that @geofffranks has already put in the `.env_hooks` to stop users from being able to generate the deployment without a vault targeted.

I think this issue is GTG.
