### ISSUE TITLE
safe tree not working on vault 0.6.0

### ISSUE THREAD

**Issue by norman-abramovitz** [jhunt/safe#31]
No good deed goes unpunished (Clare Boothe Luce)

running vault server -dev

$ safe vault list secret/aws
Keys
proto/
$ safe tree
!! secret not found
$ safe target
Currently targeting proto at http://127.0.0.1:8200
$ safe vault version
Vault v0.6.0
$ safe vault status
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0

High-Availability Enabled: false

**Comment by geofffranks** [comment]
Try `safe tree secret` or `safe tree .` ?

**Comment by jhunt** [comment]
Per the 0.6.0 changelog:

```
List operations that do not find any keys now return a 404 status code rather than an empty response object [GH-1365]
```

`safe` relies on that empty response behavior.  it needs to handle the 404 instead.  or both, preferably.  Anything that deals with tree representation will be affected.

**Comment by norman-abramovitz** [comment]
Just to answer Geoff's question both safe tree commands fail.
